INSERT INTO forecasts PARTITION(${month}) VALUES
(${id.0}, 
${tstamp},
${dt},
${temp},
${feels_like},
${temp_min},
${temp_max},
${pressure},
${sea_level},
${grnd_level},
${humidity},
${weather_id},
"${weather_main}",
"${weather_description}",
"${weather_icon}",
${clouds},
${wind_speed},
${wind_deg},
${wind_gust},
${vis},
${snow3h:isEmpty():ifElse("0", ${snow3h})},
${rain3h:isEmpty():ifElse("0", ${rain3h})},
${pop},
"${pod}"
)
